package lk.ijse.royal_care_pharmacy.dao;

public enum DaoTypes {
    MAINPAGE,LOGINPAGE,NEWACCOUNTPAGE,DASHBOARD,EMPLOYEE,SALARY,ATTENDENCE,ITEM,ORDER,ORDERDETAIL,STOCK,PAYMENT,SUPPLIER,CUSTOMER,CASHIERLOGINPAGE,STOCKMANAGERLOGINPAGE,USERSPAGE,DASHBOARDCASHIER,DASHBOARDSTM
}
