package lk.ijse.royal_care_pharmacy.service;

public enum ServiceTypes {
    MAINPAGE,LOGINPAGE,NEWACCOUNTPAGE,DASHBOARD,EMPLOYEE,SALARY,ATTENDENCE,ITEM,ORDER,ORDERDETAIL,STOCK,PAYMENT,SUPPLIER,CUSTOMER,CASHIERLOGINPAGE,STOCKMANAGERLOGINPAGE,USERSPAGE,DASHBOARDCASHIER,DASHBOARDSTM
}
